In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("taxi-trips").getOrCreate()

df = spark.read.csv("gs://bucket-name/chicago_taxi_trips.csv",header=True)

In [ ]:
df.printSchema()

In [ ]:
from pyspark.sql import functions as F

In [ ]:
df.groupby("payment_type") \
    .agg(
        F.min("fare").alias("minimum_fare"),
        F.max("fare").alias("minimum_fare")
    ).show()

In [ ]:
from pyspark.sql.types import TimestampType
df = df.withColumn("trip_start_time",df["trip_start_time"].cast(TimestampType()))
df = df.withColumn("trip_end_time",df["trip_end_time"].cast(TimestampType()))

In [ ]:
from pyspark.sql.functions import month

df = df.withColumn("trip_month",month(df.trip_start_time))

In [ ]:
df.groupby(["trip_month"]) \
    .agg(
        F.sum("trip_miles").alias("total_miles"),
        F.sum("fare").alias("total_fare")
    ).show()

In [ ]:
df.groupby(["trip_month","payment_type"]) \
    .agg(
        F.sum("trip_miles").alias("total_miles"),
        F.sum("fare").alias("total_fare")
    ).show()

In [ ]:
df.groupby(["trip_month","payment_type"]) \
    .agg(
        F.avg("fare").alias("average_fare")
    ).show()

In [ ]:
from pyspark.sql.functions import col

df = df.withColumn('trip_duration_seconds', (col('trip_end_time').cast('long') - col('trip_start_time').cast('long')))

In [ ]:
df = df.withColumn('trip_duration_minutes',(df.trip_duration_seconds/60))